### ISSUE TITLE
"Save" Button Not Working on Edit Screens

### ISSUE THREAD

**Issue by JEGeyer** [HPDCollaborative/builder-ui-beta-reporting#4] opened 2018-08-07 00:15 UTC
From the Edit screens for Materials, Substances, Certifications, and Accessories, the Save button is not working.  If you have left something out , (like R&I Notes on the Edit Material form) it catches it and provides the correct note, but it doesn't do anything if you save a complete entry.
It does work on the References, VOC, and Details forms.

**Comment by 19peaches** [comment] 2018-08-07 04:15
This is incorrect, they are working perfectly, I just added a substance, cert and accessory and all worked perfectly the very first time.

I'm going to need some sort of broken example that you can show me.

**Comment by JEGeyer** [comment] 2018-08-07 14:42
Maybe the difference was that I was editing existing records not adding new ones?
The forms I had problems with are: 
https://staging.hpd-collaborative.org/actions/4632/record -- Edit Material, Face Yarn
https://staging.hpd-collaborative.org/actions/4632/record -- Edit Substance, Nylon 6,6
https://staging.hpd-collaborative.org/actions/4632/record -- Edit Certifications, CRI Green Label Plus
https://staging.hpd-collaborative.org/actions/4632/record -- Edit Accessories, Adhesive

**Comment by 19peaches** [comment] 2018-08-07 16:33
Ok, good catch, these were caused by missing validation blocks or backend errors that weren't found on local dev. I'll need to retest the accessory error locally, as I can't before backend functions on the server.

Will update as needed.

**Comment by 19peaches** [comment] 2018-08-07 16:55
Ok all tested locally and should be fixed, pushing changes shortly.

**Closed** 2018-08-08 02:12 UTC
Labels: fixed

**Comment by JEGeyer** [comment] 2018-08-08 20:37
Confirmed this fix 8/8/18
