### ISSUE TITLE
Why are there two sections for CSI #

### ISSUE THREAD

**Issue by paviaedward** [HPDCollaborative/builder-ui-beta-reporting#36] opened 2018-08-23 19:20 UTC
I noticed on the first page of the HPD at the top you ask for Classification, and then on the bottom of the page you ask for the CSI # - isn't the Classification and the CSI# the same thing?

**Comment by 19peaches** [comment] 2018-08-23 19:42
this is a duplicate of issue #21

**Closed by 19peaches** 2018-08-23 19:42 UTC
Labels: duplicate
