### ISSUE TITLE
Make General Notes an standalone section

### ISSUE THREAD

**Issue by Millali** [HPDCollaborative/builder-ui-beta-reporting#7] opened 2018-08-07 14:59 UTC
General notes should be a standalone section as it is an independent section in the Standard and the content entered in these notes does not display anywhere else.

**Comment by 19peaches** [comment] 2018-08-07 15:56
Negative, all sections are now grouped according to the tables they live in, changing this to how it was before creates extemporaneous code, and does not follow best practices.

I'm wondering why you've been looking at this UI for several weeks and are just now telling me all these things are set up incorrectly?

The idea of this UI is to simplify the process, not to make it look like and say all the things the original one did. General Notes is part of the detail table so that's the panel it's on, changing it will require a new table and new models and major code changes.

**Comment by Millali** [comment] 2018-08-07 16:05
Hi Vince,

I have mentioned in all meetings that the text needs to be adapted and a
couple of weeks ago I expressed my concerned about the sections numbers not
matching the sections in the standard.

I understand we are simplifying the process and it is actually working but
there is a standard language and order in the HPDs that we need to mantain
so that we don't have an isolated tool. John agreed with me on this but I
am happy to leave it up to the feedback of beta users.

Milla

**Comment by JEGeyer** [comment] 2018-08-07 18:59
I agree with Milla that we need to try and tie the data being entered to where it "lives" in the HPD format. I.E. connect General Notes to "Section 5: General Notes".  And I understand that users are used to seeing the section that they're adding the information to, as a navigation tool.  
I'm also aware that users will have to adjust to the new navigation, just at they adjusted to the old system, and that we shouldn't compromise the code to make it look like they expect it to.
Milla is right that everyone (users, Technical Committee, etc.) is very conscious of the Sections and think of the HPD in that context.
We need to find a way that will make the connections Milla is looking for without compromising the code or infrastructure of the system.  If we can't change the main navigation screen, can we change the corresponding forms to add information connecting them to the appropriate Section of the Standard Format?
For Example, on the Certification, Accessory, and References forms add a line under the orange header saying "Section 3: Certifications and Compliance"; "Section 4: Accessories"; and "Section 6: References"
The other forms would be a little tougher, but both the Materials and Substances forms could say "Section 2: Content in Descending Order of Quantity" and the VOC Form could say "Section 1: Summary".
General Information would be the most complex, but I'm thinking that we could do the same thing but at the data element level instead of for the whole screen.  There we'd add a line between the title and the data field that would identify where the data would show up in the HPD. So, Classification, Product Description, and Inventory & Screening notes would have: "Section 1: Summary". General Notes would have: Section "5: General Notes", Threshold would have "Section 2: Content in Descending Order of Quantity" and we still have to talk about the CSI Division and CSI Section when we talk about publishing.
Milla, would this do what your looking for?
Vince, is this doable with little effort and not compromising the code, or infrastructure of the system?

**Comment by 19peaches** [comment] 2018-08-08 02:58
During many talks we've had in zoom, we discussed the importance of realizing that the builder is the builder, and not the standard itself. How HPD's are built and created makes absolutely no difference, as long as they match the standard when the HPD is spit out. We could create a single form with all the fields from all the screens in it ... and that would be just as valid a way to do it (although not so user friendly) but valid nonetheless.

The past does not equal the future ... 

We need to stop trying to go back to old titles and old formats that no one liked in the first place, and help move the builder forward to become a more elegant and progressive tool that will carry us into the future. The builder is evolving, growing, changing. Soon we'll be adding new fields for the users... this is just another form of evolution of a product to make it better and more inline with what was intended in the first place.

This is the whole reason that want to beta this to actual users ... let's focus on the bugs and things that aren't working correctly, and let the beta users tell us what they want to see, if they want some sort of text titles on the panels, we can do that, but let's focus on errors for now and not semantics please.

**Comment by JEGeyer** [comment] 2018-08-09 01:04
I agree that we're trying to move into the future but, as we do so, we still need to make it recognizable to the current users.  Milla is correct, the Builder users are used to thinking of the HPD as the 6 sections that make up the document format.  The Standard, our existing website help resources, all discussion of the HPDs from the technical committee, etc, all talk about these sections.  In fact that format **is** the HPD, the tool is just how we create it.  That is not to say that the tool has to mimic that format slavishly -- we all know the mostly bad response to the WYSIWYG format...  but we need to be able to relate what is in the new navigation to the 6 sections , at least on this first roll-out of the new UI.
I talked to Luke Zhou, one of our beta tester, after another meeting today and showed him the UI.  He liked it very much and did not think that the problems around this issue were all that bad, but he did jump on the fact that we needed to give more attention to how to tie what we're doing in the Builder navigation to the HPD sections.  Especially in reviewing the results of the completeness check -- since it is organized by the 6 HPD sections, he thought the user would have trouble knowing exactly where to go to fix the items that didn't pass the completeness check.
I don't want to change the coding or foundation of what already has been done -- But I do want to look at compromises that we can make by adding/modifying text on the forms to help relate the new UI to the HPD format that is how users think about the HPD.  So I'll again offer the suggestions in my earlier comment about how we might do that.  Luke also offered that he thought that taking the numbers off the main Navigation items would be helpful, as numbering them suggests that they need to be done in order, and draws attention to the differences in the new navigation and the HPD section numbers.
Let's see what kind of compromise we can come up with, with the least effort.  We may need to hash this out in a meeting where we can look at the screens and brainstorm what can be done most easily while still addressing the underlying concerns.

**Comment by JEGeyer** [comment] 2018-08-09 14:46
I reviewed the UI with Ed Pavia, another of our beta testers after a meeting that I had with him this morning.  He was very positive overall but he too thought we needed to do more to make the connection to the HPD format sections.  He agreed that the numbers on the navigation pane might confuse some people but he thought the order of the navigation elements made sense and were in the order that he would work on them.  He thought that added the suggest text to the forms would be enough to tie the navigation to the HPD sections.

**Comment by 19peaches** [comment] 2018-08-09 21:18
I would submit that the only section that needs some sort of documentation would be the first section where we've combined general notes (a single field section) it just seemed stupid to create all that infrastructure and wiring for a single field, especially when that field is stored in the same table as everything else in section 1. I think perhaps just an alert text at the top of the telling the users that we've combined these sections because it makes more sense to group them together.

I also don't wont to go overboard here, there's a point where we are just assuming that the users are too stupid to figure it out, and we certainly don't want that. I think that small cues that aren't distracting would be the best way to move forward.

So the consensus then is that we should remove the numbers on the navigation?

**Comment by JEGeyer** [comment] 2018-08-09 21:30
Yes, the consensus is to remove the numbers but leave the text as it is.
I'm also OK with starting with the first section and keeping the text low key for now, as long as we address the content inventory items as well as the general notes.
Both Ed and Luke, liked the idea of information being provided on each of the sections but, since they didn't see it as as big a deal as Milla and I did, I'm willing to address this more fully with the whole beta test team.  And, again, I'm more interested in getting the rest of the functionality ready to roll out to them.

**Comment by 19peaches** [comment] 2018-08-09 22:13
Added alert text block to GI panel.

**Comment by 19peaches** [comment] 2018-08-11 09:48
closing this in lieu of a new issue if needed.

**Closed by 19peaches** 2018-08-11 09:48 UTC
Labels: fixed
